### ISSUE TITLE
Concerts Page--List Group

### ISSUE THREAD

**Issue by AaronLain** [nss-evening-cohort-11/bands-alestorm#1]
## User Story
As a user, I want to see a list of all the cities my favorite band will be playing. I would also like to add my own city to the list

## AC

WHEN the page loads, I should see a list group of cities and a form at the bottom.
THEN I should be able to enter my city in the submit form
AND my city should appear in the list group hashtag-lit

## Dev Notes

* Use a bootstrap list group and print dynamically using ```domString``` and ```printToDom``` function. 

```
<div class="list-group">
  <a href="#" class="list-group-item list-group-item-action active">
    Cras justo odio
  </a>
  <a href="#" class="list-group-item list-group-item-action">Dapibus ac facilisis in</a>
  <a href="#" class="list-group-item list-group-item-action">Morbi leo risus</a>
  <a href="#" class="list-group-item list-group-item-action">Porta ac consectetur ac</a>
  <a href="#" class="list-group-item list-group-item-action disabled">Vestibulum at eros</a>
</div>
```
* Print the list group from an array of city objects (of your choice! At least 10) in main.js. Each object should have a City property and a date property that will appear on each list item/button.

*Clicking on the date/city list item will trigger an event listener that calls a function called ```buyTicketAlert``` which uses ```window.alert``` that says:

```
"You have bought tickets for ${city.name)! Thank you for your purchase!" 
```

**Comment by zoeames** [comment]
This needs to be broken into 2 tickets - one for displaying all cities and one for adding a new city.  Both tickets need more dev details - are you adding event listeners?  do those call functions?  what are the functions named?
