### ISSUE TITLE
About page

### ISSUE THREAD

**Issue by AaronLain** [nss-evening-cohort-11/bands-alestorm#10]
## User Story
I should see more pirate ipsum text beside some cool pics of the band
## AC
WHEN the page loads
THEN containers with text and images appear
AND nothing breaks?
## Dev Notes
* "About" is an ```h1``` 
* Hard coded into ```./about.html```
* Include 2 divs with 2 columns each, one for text, one for an image. 
* use ```col-6``` on all columns
* Alternate image and text on each div to look like the wireframe below
![image](https://user-images.githubusercontent.com/13320382/74206442-1fe66700-4c41-11ea-977a-b8703d5a721b.png)

**Comment by zoeames** [comment]
* its kinda silly to do this stuff in a domString builder.  Makes more sense to hard code.

* What else could you do on this page that would involve looping over something?
