### ISSUE TITLE
Wireframes

### ISSUE THREAD

**Issue by zoeames** [nss-evening-cohort-11/bands-alestorm#11]

**Comment by wickedanna** [comment]
[AlestormColorPalette.pdf](https://github.com/nss-evening-cohort-11/bands-alestorm/files/4183676/AlestormColorPalette.pdf)

**Comment by wickedanna** [comment]
<img width="935" alt="Screen Shot 2020-02-10 at 6 30 42 PM" src="https://user-images.githubusercontent.com/55811958/74202902-764ca900-4c33-11ea-8a04-713da732c258.png">

**Comment by wickedanna** [comment]
![ConcertMockup](https://user-images.githubusercontent.com/55811958/74202931-911f1d80-4c33-11ea-87b3-76524e689e84.PNG)

**Comment by wickedanna** [comment]
![Screen Shot 2020-02-10 at 18 30 03](https://user-images.githubusercontent.com/55811958/74202941-954b3b00-4c33-11ea-842f-db29ec2bbf92.png)

**Comment by wickedanna** [comment]
<img width="1025" alt="Screen Shot 2020-02-10 at 6 32 07 PM" src="https://user-images.githubusercontent.com/55811958/74202969-a98f3800-4c33-11ea-95d1-75856fb0d516.png">

**Comment by wickedanna** [comment]
![image](https://user-images.githubusercontent.com/55811958/74203211-65506780-4c34-11ea-8bad-3aacfa7aabac.png)
