### ISSUE TITLE
Concerts Page--Form Loop

### ISSUE THREAD

**Issue by AaronLain** [nss-evening-cohort-11/bands-alestorm#2]
## User Story
When I enter my hometown in the concert page form, my city should appear in the list of cities.

## AC
WHEN I enter my hometown into the form and push submit
THEN the page reloads 
AND my city has been added to the list of cities with a randomly generated date.

## Dev Notes
* Place a bootstrap form below the list group 
https://getbootstrap.com/docs/4.0/components/forms/

![image](https://user-images.githubusercontent.com/13320382/73892573-ebd40600-483c-11ea-95ee-9e0a40074fdf.png)

* Add an event listener to the form's submit button (```id="city-submit"```). 

* Write a function called ```addCity``` that passes the input from the form into the array of cities called ```cities```  using ```prototype.push()``` . Have the page reload when the submit button is pressed. When the page reloads, the new city should appear in the list group. 

* Generate a random date with the ```dd/mm/yyyy``` format using ```Math.ceil(Math.random())``` for each of the numbers. Pass this date into the array when the submit button is pressed and call it with ```${city.date}```.

**Comment by zoeames** [comment]
this needs some more dev details.  when should the info from the input get pulled?
