### ISSUE TITLE
Merch Page--Buttons

### ISSUE THREAD

**Issue by AaronLain** [nss-evening-cohort-11/bands-alestorm#3]
## User Story
This is about buttons. I should be able to click on a button and have the merch sorted accordingly. 

## AC
WHEN the page loads 
THEN the buttons should load 
AND when clicked, sort the cards according to their labels.

## Dev Notes
*  Create four bootstrap buttons ```<button type="button" class="btn btn-info">Info</button>``` 
*  Label each button ```Clothing, CD's, On Sale, All```
* Attach an ```eventListener``` to each button that reloads the ```domString``` and sorts the cards based on the button label. At the press of each button, the ```printToDom```  and ```buildMerchCards``` functions are called.
![image](https://user-images.githubusercontent.com/13320382/73893490-73227900-483f-11ea-9fff-f38b705251a1.png)
* Write  function called ```merchSort``` that reloads the page, displaying the cards whose ```e.target.id``` matches the ```$(merch.type)```. There should be an if statement that checks if the button pressed is the ```All``` button and should display all merch when pressed. ```else``` the function iterates through the ```merch``` array and displays only those cards whose id's match the button.
* The button id's should match their labels i.e. ```id="clothing"```, ```id="cd"```, ```id="on-sale"```, and ```id="all"```.

**Comment by zoeames** [comment]
more dev details - what are your functions called?  what do they do?

**Comment by wickedanna** [comment]
changed color from ``` btn-info ``` to ``` btn-warning ``` because info blended into the background too much, also needed two functions instead of one to get sale button to work, so function names are slightly different than ticket defined.

**Comment by Jmarquez8951** [comment]
👍
