### ISSUE TITLE
Merch Page--Cards

### ISSUE THREAD

**Issue by AaronLain** [nss-evening-cohort-11/bands-alestorm#4]
## User Story 
I should see rows of (3) cards display below the sorting buttons. Each card should have a item name, a picture of the item as well as a price and description and a buy now button

## AC
WHEN the page loads
THEN the merch cards should appear on the page
AND I can click "buy now" to purchase said item

## Dev Notes
* Use a ```printToDom``` and a ```buildMerchCards``` function to dynamically print the merch cards on the page using ```domString```. The data on the merch cards will be populated from an array called ```merch```. 
* The card should display a title which will contain the item's name, an image of the item, a description, and a price. Below everything will be a button that says 'Buy Now'. 
* The cards should be bootstrap cards  
```
<div class="card" style="width: 18rem;">
   <h5 class="card-title">Card title</h5>
  <div class="card-body">
    <img class="card-img-top" src="..." alt="Card image cap">
    <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
    <a href="#" class="btn btn-primary">Go somewhere</a>
  </div>
</div>
```
![image](https://user-images.githubusercontent.com/13320382/73893866-72d6ad80-4840-11ea-8761-02dfefde0496.png)

For the button see issue #13

**Comment by AaronLain** [comment]
Nine cards total

**Comment by zoeames** [comment]
* More dev notes needed
* split this into 2 tickets - one for making the cards, one for the Buy Now button

**Comment by AaronLain** [comment]
Card Items:
CD: Title: Captain Morgan's Revenge (track list array: 1.  "Over the Seas"  2.  "Captain Morgan's Revenge" 
 3.  "The Huntmaster"  4.  "Nancy the Tavern Wench"  5.  "Death Before the Mast" )

Clothing: Kilt 

CD: Black Sails at Midnight (track list array: 1.  "The Quest" (Christopher Bowes) 2.  "Leviathan" (Bowes) 3.  "That Famous Ol' Spiced" 4. "Keelhauled" 5. "To the End of Our Days"  6. "Black Sails at Midnight")

Clothing: Tank Top

Clothing: Beanie

CD: Curse of the Crystal Coconut (track list array: 1. "The Coconut Calls" 2: "Tales from the Coconut Crypt" 3: "Old Man River (cover)" 4: "Why's the Rum Gone?" 5: "You Drive me Coco-nutty" 6: "Nutella"

Clothing: T-Shirt

Clothing: T-Shirt#2

Clothing: Hoodie
