### ISSUE TITLE
Home Page--Image Header and Title

### ISSUE THREAD

**Issue by AaronLain** [nss-evening-cohort-11/bands-alestorm#5]
## User Story
I should see a dope header image with an overlayed title of the band across it. 

## AC
WHEN the page loads
THEN I should see a sick-ass header image
AND the name of the band should be overlayed on the image
AND I will not cry

## Dev Notes
* In the index.html, hard code a header div with an image that stretches across the width of the page beneath the nav bar. 
* use a bootstrap display heading and overlay that text over the image in a cool way
```<h1 class="display-1">Display 1</h1>```
* When I click on the image it will use an ```<a href="link">``` tag and takes me to a youtube video of one of alestorm's songs (Mexico)
*  (stretch) include some fancy animation maybe or parallax

**Comment by zoeames** [comment]
" click on the image" does this mean you are using an <a> tag?  or are you using a button?  if you are using a button you should have some JS notes here
