### ISSUE TITLE
Home Page--Concerts

### ISSUE THREAD

**Issue by AaronLain** [nss-evening-cohort-11/bands-alestorm#6]
## User Story
I should see a Concerts section load below the image header. I should see text on the right and a button on the left that takes me to the concert page. 
## AC
WHEN the page loads 
THEN the concert section should load below the header image
AND the button should take the user to the concerts page
## Dev Notes
* "Live Shows!" should be an ```h2```
* Use a ```domString``` and a ```printToDom``` to dynamically create a concert section/div. The text should be pirate ipsum and the button should be a bootstrap button that says "Buy Tickets!". 
![image](https://user-images.githubusercontent.com/13320382/73895085-09589e00-4844-11ea-8c73-b5e719c5646d.png)
* The left column (```col-8```) should contain pirate Ipsum text while the right holds a button (```col-4```). 

https://getbootstrap.com/docs/4.0/layout/grid/

*The 'Buy Tickets!' button will contain a ```<a href="./concerts.html">``` that takes the user to the concerts page

**Comment by zoeames** [comment]
* More dev details
* what does the buy tickets button do?
