### ISSUE TITLE
Home Page--Merch

### ISSUE THREAD

**Issue by AaronLain** [nss-evening-cohort-11/bands-alestorm#7]
## User Story
I should see a merch section with 3 image cards that take me to the merch page

## AC
WHEN the page loads
THEN the Merch section should load below the Concerts section
AND when I click on an image, it takes me to the merch page
AND (stretch) when I mouseover the card I should see a text overlay that says "Buy now!"

## Dev Notes
* "Merch!" should be an ```h2```
* Use a ```buildHomepageMerch``` and ```printToDom```functions to print a title and 3 image cards inside a div (```id="merch-home"```).
https://getbootstrap.com/docs/4.0/components/card/
![image](https://user-images.githubusercontent.com/13320382/73895622-cef00080-4845-11ea-9f18-53950387926d.png)
* Create a new array called ```homePageMerch``` populated by the items in the ```merch``` array whose ```onSale``` value is ```true```. 
* Attach  ```<a href="./merch.html">``` to the image to link it to the merch page.

**Comment by AaronLain** [comment]
![image](https://user-images.githubusercontent.com/13320382/73895689-0c548e00-4846-11ea-8fc3-4b6376c5f43f.png)

**Comment by zoeames** [comment]
* More dev details on functions
