### ISSUE TITLE
Nav Bar

### ISSUE THREAD

**Issue by AaronLain** [nss-evening-cohort-11/bands-alestorm#8]
## User Story
I should see the same nav bar on every page and lcikcing the button should take me to the corresponding page
## AC
WHEN the page loads
THEN I should see a nav bar
AND I should be able to click it and have another page load
## Dev Notes
* Use a bootstrap nav bar and hard code it into ```index.html```, ```merch.html```, ```concerts.html```,```about.html```
![image](https://user-images.githubusercontent.com/13320382/73895861-aae0ef00-4846-11ea-9cf2-318be5ea0b06.png)
https://getbootstrap.com/docs/4.0/components/navbar/
* Link each button to  ```index.html```, ```merch.html```, ```concerts.html```,```about.html```

**Comment by zoeames** [comment]
good!
