### ISSUE TITLE
Footer

### ISSUE THREAD

**Issue by AaronLain** [nss-evening-cohort-11/bands-alestorm#9]
## User Story
At the bottom of each page I should see a footer with copyright material and the year etc. 
## AC
WHEN the page loads
THEN I should see a footer at the bottom of the page
## Dev Notes
Hardcode a footer into ```index.html```, ```merch.html```, ```concerts.html```,```about.html``` with its own div. 
![image](https://user-images.githubusercontent.com/13320382/73896053-42464200-4847-11ea-8d28-6fb82c10927b.png)
 *MAke it say the year and copyright.
* (stretch) put social media links up on it

**Comment by zoeames** [comment]
good
